spring:
   datasource:
      username: intensives
      password: intensives
      url: jdbc:mysql://localhost:3306/intensives
      
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true